### ISSUE TITLE
OpenGraph/Other Meta Tags

### ISSUE THREAD

**Issue by vincent404** [cosmicradiotv/u62-theme#6]
Make sure all meta data is generated on a per post basis and editable on the site as a whole. Including this here, but may be factored out into a separate plugin.

**Comment by blendermf** [comment]
I think because this will probably tie really close to the podcast plugin, I may just implement it there, or in a small plugin that depends on the main plugin. I think it makes sense for that data to be there in general anyways (and maybe turned on and off with a setting). Anything that is very specific to us I'll probably do in the theme. Because of that I'll close this for now.
